pipeline:

  # run_tests:
  #   image: docker:17.09.0-ce
  #   environment:
  #     - TZ=Europe/Stockholm
  #     - DOCKER_HOST=unix:///var/run/docker.sock
  #     - DRONE_REPO=iteam1337/delete-me
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:rw
  #   commands:
  #     - docker build --pull --rm -t iteam1337/delete-me:test -f ./Dockerfile.test .
  #     - docker run --rm iteam1337/delete-me:test
  #   when:
  #     event: [push, pull_request, tag]

  clair:
    image: jmccann/drone-clair:1
    url: http://192.168.100.41:6060
    username: ${docker_username}
    password: ${docker_password}
    scan_image: iteam1337/af-kompetenskartlaggning-api:ci
    secrets: [ docker_username, docker_password ]
