pipeline:

  run_tests:
    image: docker:17.09.0-ce
    environment:
      - TZ=Europe/Stockholm
      - DOCKER_HOST=unix:///var/run/docker.sock
      - REPO=${DRONE_REPO}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
    commands:
      - docker build --pull --rm -t ${REPO}:test -f ./Dockerfile.test .
      - docker run --rm ${REPO}:test
    when:
      event: [push, pull_request, tag]
